### ISSUE TITLE
Export gh_token()?

### ISSUE THREAD

**Issue by hadley** [r-pkgs/gh#39]
Or provide some way to prospectively determine if the user has credentials in place.

**Comment by hadley** [comment]
I'm mostly imagining this would be a place to hang the documentation for how to set up your `GITHUB_PAT` env var, and to give users a way to check that they're correctly configured.

**Comment by gaborcsardi** [comment]
We can also just document that `Sys.getenv()` queries it, no? :)
I am just the devil's advocate, minimizing the number of exported functions....

**Comment by gaborcsardi** [comment]
I think this would make sense, but I want to wait a bit for https://github.com/MangoTheCat/keyring improvements, because that could be another good (even better?) location to get the token or a GH password from. Then we can have a generic `gh_auth()` function that works on tokens in env vars, token in the OS keyring, and passwords in the OS keyring.

**Comment by hadley** [comment]
Agreed.
